package com.libro2.unidad1;

public class CommentsExamples {

    //Multiline commentscstart with /* and end with */
/*
comments that span multiple
lines of code
 */


//Multiline comments can contain special characters in it.

    /*
    Multi line comments with
    special characters /%*´+Ñ[ñ{,.-'¿}
     */


    /*
    *comments that span multiple
    * lines of code
    */


    public static void main(String[] arg) {

        String fName; //variable to store Person´s first name
        String id; // a 6 letter id generated by the database


        String name = /* Harry */ "Paul";
        System.out.println("name " + name);


        String name2 = "/* Harry */ Paul";
        System.out.println("name " + name2);

        //no compila lo siguiente si lo descomentamos:
        //String name2 = "Shre /*ya
         //                    */ Paul";
        //System.out.println("name " + name3);

       
    }

}
